### ISSUE TITLE
How do I install this cow B plugin in code server

### ISSUE THREAD

**Issue by wgqi1126** [SaekiRaku/vscode-rainbow-fart#69]
How do I install this cow B plugin in code server

https://github.com/cdr/code-server

VS Code in the browser https://coder.com

**Comment by SaekiRaku** [comment]
I haven't used `code-server` before, I only have simply tried it just now. It may not the best practice, be careful when you do follow steps in a production environment. Here is my steps:

1. Download the VSIX version of this extension. (I don't know why it can't be found in the code-server VSCode market place)
2. Start the code-server. I used docker, make sure you can reach the VSIX file inside the container. And also make sure the port of `7777` can be reached outside the container and the server. Here is my `docker-compose` config file:

```yml
version: "3.7"
services:
  nginx:
    image: codercom/code-server:latest
    ports:
      - "127.0.0.1:8080:8080"
      - "7777:7777"
    volumes:
      - ./project:/home/coder/project
      - ./extension:/home/coder/extension
```

3. Open the code-server with your browser, then run VSCode command `> Extensions: Install from VSIX`, then select the VSIX file.
4. Run VSCode command `> Enable Rainbow Fart` to activate the extension. A notification should be popped up at the corner, ignore it.
6. Open the browser and visit this URL: `http://${SERVER_IP}:7777`, then click `Authorization`.
7. Enjoy coding on your code-server.

You must have the full control of the server that running the `code-server`, because you need to make the port of 7777 can be reached.
